dist: bionic

language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  - CONTAO_VERSION=4.9

matrix:
  allow_failures:
    - php: "7.1"

jobs:
  exclude:
  - php: "7.1"
    env: CONTAO_VERSION=4.9

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core-bundle:$CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest

script: 
  - vendor/bin/phpunit
  - vendor/bin/psalm

cache:
  directories:
    - vendor